### ISSUE TITLE
`require` cannot load such module

### ISSUE THREAD

**Issue by sahilsehwag** [RRethy/tagrity#5]
traceback (most recent call last):
	16: from /usr/local/bin/tagrity:23:in `<main>'
	15: from /usr/local/bin/tagrity:23:in `load'
	14: from /Library/Ruby/Gems/2.6.0/gems/tagrity-0.3.8/exe/tagrity:3:in `<top (required)>'
	13: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	12: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /Library/Ruby/Gems/2.6.0/gems/tagrity-0.3.8/lib/tagrity/cli.rb:2:in `<top (required)>'
	10: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	9: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	8: from /Library/Ruby/Gems/2.6.0/gems/tagrity-0.3.8/lib/tagrity/commands/start.rb:5:in `<top (required)>'
	7: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	6: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	5: from /Library/Ruby/Gems/2.6.0/gems/tagrity-0.3.8/lib/tagrity/provider.rb:2:in `<top (required)>'
	4: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	3: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	2: from /Library/Ruby/Gems/2.6.0/gems/tagrity-0.3.8/lib/tagrity/tag_generator.rb:5:in `<top (required)>'
	1: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- pry (LoadError)

**Comment by sahilsehwag** [comment]
Fixed this by manually installing `pry`, `tagrity` is not automatically installing all the required dependencies

**Comment by RRethy** [comment]
`pry` is a dev dependency for `tagrity` which is why it wasn't installed, there was a stray `require 'pry'` in the source code which has been removed, if you upgrade to 0.3.9 it won't error if you dodn't have pry installed.
